// Vicuna seal logo (direction #3): a line-drawn bow inside a ring.
// Master vector files live in brand/ (generated by brand/make_logo.py with text outlined).

/** The bow, drawn on a 100×100 grid. */
export const BOW_PATHS = (color: string, sw = 3.2) =>
  `<path fill="none" stroke="${color}" stroke-width="${sw}" stroke-linejoin="round" d="M50 50C38 30 16 24 14 38C12 52 34 56 50 50ZM50 50C62 30 84 24 86 38C88 52 66 56 50 50Z"/>` +
  `<rect x="44" y="44" width="12" height="12" rx="3.5" fill="${color}"/>` +
  `<path d="M47 56C42 66 36 74 30 82M53 56C58 66 64 74 70 82" fill="none" stroke="${color}" stroke-width="${sw}" stroke-linecap="round"/>`;

/** Ring + bow: the compact mark used at small sizes. */
export const LogoMark = ({ size = 40 }: { size?: number }) => (
  <svg
    className="logo-mark"
    width={size}
    height={size}
    viewBox="0 0 200 200"
    aria-hidden="true"
    dangerouslySetInnerHTML={{
      __html: `<circle cx="100" cy="100" r="88" fill="none" stroke="var(--ink)" stroke-width="7"/><g transform="translate(34 30) scale(1.32)">${BOW_PATHS("var(--accent)", 4.4)}</g>`,
    }}
  />
);

export const Logo = ({ sub = "فيكونا" }: { sub?: string }) => (
  <span className="logo">
    <LogoMark />
    <span className="logo-word">
      <span className="logo-en">VICUNA</span>
      <span className="logo-ar">{sub}</span>
    </span>
  </span>
);

/** Favicon as a data URI (fixed colours, works on any tab background). */
export const faviconHref =
  "data:image/svg+xml," +
  encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><rect width="200" height="200" rx="44" fill="#FFF5F3"/><circle cx="100" cy="100" r="86" fill="none" stroke="#3A1F26" stroke-width="6"/><g transform="translate(34 30) scale(1.32)">${BOW_PATHS("#B5476A", 4)}</g></svg>`,
  );
